build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.22"
  amd64: "ghcr.io/home-assistant/amd64-base:3.22"
  armhf: "ghcr.io/home-assistant/armhf-base:3.22"
  armv7: "ghcr.io/home-assistant/armv7-base:3.22"
  i386: "ghcr.io/home-assistant/i386-base:3.22"

labels:
  org.opencontainers.image.title: "Home Assistant Add-on: RelayPrint Server"
  org.opencontainers.image.description: "Home Assistant add-on to relay print jobs via CUPS and secure tunnels"
  org.opencontainers.image.source: "https://github.com/samuelmukoti/ha-printer-relay"
  org.opencontainers.image.licenses: "Apache-2.0"
